#!/bin/bash

#import functions
source ./Data/functions

#test for the valid imput
bash ./Data/test $@


description=$3
tmp=$(echo ${description// /_})
description=$tmp


config=./configure/$1_$2.vbash

cp $config ./configure.vbash

echo -e $description '\n'$4 $5 > input.txt

#connect
user=admin
ip=192.168.168.1
key=./key
port=22
file="configure.vbash setup.vbash Data tmp input.txt"
scp -P $port -i $key -r $file $user@$ip:~
ssh -p $port -q $user@$ip -i $key vbash setup.vbash
ssh -p $port -q $user@$ip -i $key rm -r $file
rm configure.vbash

