#!/bin/bash                                                                     
cd ./edge     
 
#import functions
source ./Data/functions

#test for the valid imput
bash ./Data/test $@
 
description=$3                                                           
tmp=$(echo ${description// /_})         
description=$tmp
  
              
config=./configure/$1_$2.vbash 
                
cp $config ./configure.vbash

echo -e $description '\n'$4 $5 > input.txt

                            
file="configure configure.vbash setup.vbash Data tmp input.txt"
cp -r $file  ../                          
cd ../
vbash setup.vbash
rm -r $file  
